window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t456_setListMagin(recid,imglogo){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<=980)return;var menu=rec.querySelector('.t456');var leftSide=menu?menu.querySelector('.t456__leftwrapper'):null;var list=menu?menu.querySelector('.t456__list'):null;var leftSideWidth=leftSide?leftSide.offsetWidth:0;if(list)list.style.marginRight=(imglogo?leftSideWidth:leftSideWidth+30)+'px'}
function t451_initMenu(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;t_onFuncLoad('t_menuWidgets__init',function(){t_menuWidgets__init(recId)});var burgerList=rec.querySelectorAll('.t451 .t-menuburger');var menu=rec.querySelector('.t451m');var menuBlock=rec.querySelector('.t451');var overlay=rec.querySelector('.t451m__overlay');Array.prototype.forEach.call(burgerList,function(burger){burger.addEventListener('click',function(e){e.preventDefault();t451_closeMenu(menu,overlay);t451_showMenu(menu,overlay);t451_checkSize(menu)})});if(menu){menu.click(function(e){t451_closeMenu(menu,overlay);t451_showMenu(menu,overlay);t451_checkSize(menu);e.preventDefault()})}
if(menuBlock){menuBlock.addEventListener('clickedAnchorInTooltipMenu',function(){t451_closeMenu(menu,overlay)})}
rec.addEventListener('click',function(e){if(window.innerWidth>980)return;var submenuClassList=['.t451__link-item_submenu','.t966__tm-link','.t978__tm-link','.t978__menu-link_hook',];var isContainsSubmenuClass=submenuClassList.some(function(className){return e.target.closest(className)});if(!isContainsSubmenuClass)return;setTimeout(function(){t451_checkSize(menu)},100)});window.addEventListener('resize',function(){t451_checkSize(menu)});menu.addEventListener('menuOverflow',function(){t451_checkSize(menu)});var navLinks=rec.querySelectorAll('.t451 a.t-menu__link-item[href*="#"], .t451 a.t-menusub__link-item[href*="#"]');navLinks=Array.prototype.filter.call(navLinks,function(navLink){return!navLink.classList.contains('tooltipstered')});if(navLinks.length>0){t_onFuncLoad('t_menu__updateActiveLinks',function(){t_menu__updateActiveLinks(navLinks,'.t451')})}
t_onFuncLoad('t_menu__highlightActiveLinks',function(){t_menu__highlightActiveLinks('.t451m__menu a')});document.addEventListener('click',function(e){if(e.target.closest('.t451m__overlay, .t451m__close, a[href*="#"]:not(.tooltipstered):not(.t794__tm-link):not(.t978__tm-link):not(.t966__tm-link):not(.t978__menu-link_hook):not(.t-menuwidgeticons__link_wishlist):not(.t-menuwidgeticons__link_cart)')){t451_closeMenu(menu,overlay)}});document.addEventListener('keydown',function(e){if(e.keyCode===27){t451_closeMenu(menu,overlay)}})}
function t451_showMenu(menu,overlay){if(!menu)return;if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t451__body_menushowed');menu.classList.add('t451m__menu_show');if(overlay)overlay.classList.add('t451m__menu_show')}
function t451_closeMenu(menu,overlay){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t451__body_menushowed');if(menu)menu.classList.remove('t451m__menu_show');if(overlay)overlay.classList.remove('t451m__menu_show')}
function t451_checkSize(menu){if(!menu)return;var menuTop=menu.querySelector('.t451m__top');var menuRight=menu.querySelector('.t451m__rightside');var menuContainer=menu.querySelector('.t451m__container');var menuTopHeight=menuTop?menuTop.offsetHeight:0;var menuRightHeight=menuRight?menuRight.offsetHeight:0;var windowPadding=80;if(menuTopHeight+menuRightHeight+windowPadding>window.innerHeight){menu.classList.add('t451m__overflowed');if(menuContainer)menuContainer.style.height='auto'}else{menu.classList.remove('t451m__overflowed');if(menuContainer)menuContainer.style.height=''}}
function t451_appearMenu(recId){var rec=document.getElementById('rec'+recId);var burger=rec?rec.querySelector('.t451__panel'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';if(burgerAppearOffset)burgerAppearOffset=t451_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t451__beforeready')){burger.classList.remove('t451__beforeready')}}else{burger.classList.add('t451__beforeready')}}
function t451_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor(window.innerHeight*(parseInt(string,10)/100))}
return parseInt(string,10)}
function t585_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var accordion=rec.querySelectorAll('.t585__accordion')[0];var headers=rec.querySelectorAll('.t585__header');var undercuts=rec.querySelectorAll('.ql-undercut');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var accordionScroll;if(accordion){accordionScroll=accordion.getAttribute('data-scroll-to-expanded');accordion=accordion.getAttribute('data-accordion')}else{accordion='false';accordionScroll='false'}
for(var i=0;i<headers.length;i++){headers[i].addEventListener('click',function(){var element=this;var container=element.nextElementSibling;var triggerButton=element.querySelector('.t585__trigger-button');var activeHeight=0;var isAccordionDown=!1;if(triggerButton){var isExpanded=triggerButton.getAttribute('aria-expanded')==='true';triggerButton.setAttribute('aria-expanded',!isExpanded);container.hidden=isExpanded}
if(element.classList.contains('t585__opened')){element.classList.remove('t585__opened');t585_accordionHide(container)}else{if(accordionScroll==='true'&&accordion==='true'){activeHeight=t585__getOldAction(rec);isAccordionDown=t585__getAccordionPosition(headers,element)}
if(accordion==='true')t585_accordionAllHide(headers);element.classList.add('t585__opened');container.style.display='block';var height=container.scrollHeight;container.style.maxHeight='0px';setTimeout(function(){container.style.maxHeight=height+'px';if(accordionScroll==='true'){t585__calcHeight(element,container,activeHeight,isAccordionDown)}},0)}
if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
for(var i=0;i<undercuts.length;i++){undercuts[i].addEventListener('click',function(event){const target=event.target;const content=target.closest('.t585__content');const textBlock=target.closest('.t585__textwrapper');setTimeout(()=>{content.style.maxHeight=textBlock.scrollHeight+'px'},0)})}}
function t585_accordionAllHide(headers){for(var i=0;i<headers.length;i++){var elementHide=headers[i];elementHide.classList.remove('t585__opened');t585_accordionHide(elementHide.nextElementSibling)}}
function t585_accordionHide(container){if(!container.style.maxHeight)container.style.maxHeight=container.scrollHeight+'px';setTimeout(function(){container.style.maxHeight='0px'},0)}
function t585__getOldAction(rec){var activeHeader=rec.querySelector('.t585__opened');var activeHeight=0;if(activeHeader)var activeContainer=activeHeader.nextElementSibling;if(activeContainer)activeHeight=activeContainer.offsetHeight;return activeHeight}
function t585__getAccordionPosition(headers,element){var oldIndex;var newIndex;for(var i=0;i<headers.length;i++){var header=headers[i];if(header.classList.contains('t585__opened'))oldIndex=i;if(header===element)newIndex=i}
return oldIndex<newIndex?!0:!1}
function t585__calcHeight(element,container,activeHeight,isAccordionDown){var windowHeight=window.innerHeight;var windowScroll=window.scrollY;var containerHeight=container.scrollHeight;var accordionHeight=containerHeight+element.offsetHeight;var elementTopOffset=element.getBoundingClientRect().top+windowScroll;var target=isAccordionDown?elementTopOffset-activeHeight:elementTopOffset;var accordionBottomLine=target+accordionHeight;var windowBottomLine=windowScroll+windowHeight;if(target<windowScroll||accordionHeight>windowHeight||accordionBottomLine>windowBottomLine){t585__scroll(target)}}
function t585__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t585__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return(change/2)*currentTime*currentTime*currentTime+start}else{return(change/2)*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t585__animateScroll(){currentTime+=increment;window.scrollTo(0,t585__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t585__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t585__animateScroll()}
function t121_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var wrapperBlock=rec.querySelector('.t121');var videoLazy=rec.querySelector('.t-video-lazyload');if(videoLazy){t_onFuncLoad('t_video_lazyload__setHeight',function(){var videoHeight=videoLazy.getAttribute('data-videolazy-height');if(videoHeight!=='540px')return;t_video_lazyload__setHeight(videoLazy);window.addEventListener('resize',function(){t_video_lazyload__setHeight(videoLazy)});if(!wrapperBlock)return;wrapperBlock.addEventListener('displayChanged',function(){t_video_lazyload__setHeight(videoLazy)})})}
var videoCarrier=rec.querySelector('.t-video-carier');if(!videoCarrier)return;var screenMin=rec.getAttribute('data-screenmin');var screenMax=rec.getAttribute('data-screenmax');var isLoad=!1;if(window.innerWidth<parseInt(screenMin,10)||window.innerWidth>parseInt(screenMax,10))return;window.addEventListener('scroll',t_throttle(function(){if(!isLoad){var videoCarrierOffsetTop=videoCarrier.getBoundingClientRect().top+window.pageYOffset;var videoCarrierHeight=parseInt(window.getComputedStyle(videoCarrier).height,10);var windowScrollTop=window.pageYOffset;var windowHeight=window.innerHeight;if(windowScrollTop+windowHeight>videoCarrierOffsetTop-500&&windowScrollTop<videoCarrierOffsetTop+videoCarrierHeight+501){t_onFuncLoad('processYoutubeVideo',function(){processYoutubeVideo(videoCarrier,videoCarrier.style.height)});isLoad=!0}}}));var event=document.createEvent('HTMLEvents');event.initEvent('scroll',!0,!1);window.dispatchEvent(event)}
function t670_init(recid,isEditMode){var rec=document.getElementById('rec'+recid);if(!rec)return;var image=rec.querySelector('.t-img');if(image){if(image.complete){t670_addImageEvents(recid,isEditMode)}else{image.addEventListener('load',function(){t670_addImageEvents(recid,isEditMode)});image.addEventListener('error',function(){t670_addImageEvents(recid,isEditMode)})}}else{t670_addImageEvents(recid,isEditMode)}}
const t670_postMessages={youtube:{pause:'{"event":"command","func":"pauseVideo","args":""}',play:'{"event":"command","func":"playVideo","args":""}',},rutube:{pause:'{"type":"player:pause","data":"{}"}',play:'{"type":"player:play","data":"{}"}',},vimeo:{pause:'{"method":"pause","value":"true"}',play:'{"method":"play","value":"true"}',},};function t670_addImageEvents(recid,isEditMode){var rec=document.getElementById('rec'+recid);t670_imageHeight(rec);t670_show(rec);t670_hide(rec);t670_addArrowHandlers(rec);t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)});if(isEditMode){t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
var wrapper=rec.querySelector('.t670');if(wrapper){wrapper.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t_onFuncLoad('t_slds_positionArrows',function(){t_slds_positionArrows(recid)})})}}
function t670_handleRutube(videoWrap,videoLazy){var videoId=videoLazy.getAttribute('data-videolazy-id');if(videoId)videoId=videoId.replace(/[^\w-]/g,'');if(!videoId)return;var videoHash=videoLazy.getAttribute('data-videolazy-hash');if(videoHash)videoHash=videoHash.replace(/[^\w-]/g,'');var existingIframe=videoWrap.querySelector('iframe.t670__rutube-iframe');if(!existingIframe){var src='https://rutube.ru/play/embed/'+videoId+'/?autoplay=1&muted=1&playsinline=1';if(videoHash)src+='&p='+videoHash;videoWrap.innerHTML='';var iframe=document.createElement('iframe');iframe.className='t670__rutube-iframe';iframe.setAttribute('allow','autoplay; fullscreen');iframe.setAttribute('allowfullscreen','');iframe.setAttribute('frameborder','0');iframe.style.width='100%';iframe.style.height='100%';iframe.style.display='block';iframe.src=src;videoWrap.appendChild(iframe)}else{try{existingIframe.contentWindow.postMessage(t670_postMessages.rutube.play,'*')}catch(e){console.warn('Failed to send play message to Rutube iframe:',e)}}}
function t670_show(rec){var playBtns=rec.querySelectorAll('.t670__play');Array.prototype.forEach.call(playBtns,function(play){var itemWrap=play.closest('.t670__imgwrapper');var image=itemWrap.querySelector('.t-slds__bgimg');var videoWrap=itemWrap.querySelector('.t670__wrap-video');var videoLazy=videoWrap.querySelector('.t-video-lazyload');play.addEventListener('click',function(event){event.preventDefault();videoWrap.style.display='block';image.style.opacity=0;var type=videoLazy.getAttribute('data-videolazy-type');if(type==='rutube'){t670_handleRutube(videoWrap,videoLazy)}else{t_onFuncLoad('t_video_lazyload__addVideo',function(){t_video_lazyload__addVideo(videoLazy)})}})})}
function t670_pauseVideo(videoWrap){if(!videoWrap)return;var iframe=videoWrap.querySelector('iframe');if(iframe&&iframe.contentWindow&&iframe.src){var videoSRC=iframe.src;if(videoSRC.indexOf('&enablejsapi=1')!==-1){iframe.contentWindow.postMessage(t670_postMessages.youtube.pause,'*')}
if(videoSRC.indexOf('rutube')!==-1){iframe.contentWindow.postMessage(t670_postMessages.rutube.pause,'*')}
if(videoSRC.indexOf('vimeo')!==-1&&videoSRC.indexOf('&api=1')!==-1){iframe.contentWindow.postMessage(t670_postMessages.vimeo.pause,'*')}}
var videoEl=videoWrap.querySelector('video');if(videoEl&&typeof videoEl.pause==='function'){try{videoEl.pause()}catch(e){console.warn('t670: Failed to pause video element:',e)}}}
function t670_hide(rec){var videoWraps=rec.querySelectorAll('.t670__wrap-video');rec.addEventListener('updateSlider',function(){Array.prototype.forEach.call(videoWraps,function(videoWrap){t670_pauseVideo(videoWrap);var hasIframe=videoWrap.querySelector('iframe');if(!hasIframe){videoWrap.style.display='none'}})})}
function t670_addArrowHandlers(rec){if(!rec)return;if(rec.t670ArrowsInitialized){return}
rec.t670ArrowsInitialized='true';rec.addEventListener('click',function(event){var arrow=event.target.closest('.t-slds__arrow_wrapper');if(!arrow)return;t670_pauseAllVideos(rec)})}
function t670_pauseAllVideos(rec){if(!rec)return;var videoWraps=rec.querySelectorAll('.t670__wrap-video');Array.prototype.forEach.call(videoWraps,function(videoWrap){t670_pauseVideo(videoWrap);var hasIframe=videoWrap.querySelector('iframe');if(!hasIframe){videoWrap.style.display='none';var imgWrapper=videoWrap.closest('.t670__imgwrapper');if(imgWrapper){var bgImg=imgWrapper.querySelector('.t-slds__bgimg');if(bgImg){bgImg.style.opacity=1}}}})}
function t670_imageHeight(rec){var images=rec.querySelectorAll('.t670__separator');Array.prototype.forEach.call(images,function(img){var width=parseInt(img.getAttribute('data-slider-image-width'))||0;var height=parseInt(img.getAttribute('data-slider-image-height'))||0;var ratio=height/width;var padding=ratio*100;img.style.paddingBottom=padding+'%'})}
function t1061_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var wrapperBlock=rec.querySelector('.t1061');var videoLazys=rec.querySelectorAll('.t-video-lazyload');if(videoLazys.length){t_onFuncLoad('t_video_lazyload__setHeight',function(){for(var i=0;i<videoLazys.length;i++){t_video_lazyload__setHeight(videoLazys[i])}
window.addEventListener('resize',function(){for(var i=0;i<videoLazys.length;i++){t_video_lazyload__setHeight(videoLazys[i])}});if(!wrapperBlock)return;wrapperBlock.addEventListener('displayChanged',function(){for(var i=0;i<videoLazys.length;i++){t_video_lazyload__setHeight(videoLazys[i])}})})}
var thumbnails=rec.querySelectorAll('.t1061__video-thumbnail');if(!thumbnails.length)return;Array.prototype.forEach.call(thumbnails,function(thumbnail){var videoWrap=thumbnail.closest('.t1061__wrap-video');var video=videoWrap.querySelector('.t-video-lazyload');var videoId=video.getAttribute('data-videolazy-id');var videoType=video.getAttribute('data-videolazy-type');t1061__setThumbnailImg(thumbnail,videoType,videoId);thumbnail.addEventListener('click',function(event){event.preventDefault();t_onFuncLoad('t_video_lazyload__addVideo',function(){t_video_lazyload__addVideo(video);thumbnail.remove()})})})}
function t1061__setThumbnailImg(thumbnailEl,videoType,videoId){function setBgImage(url){thumbnailEl.style.backgroundImage=url}
if(videoType==='youtube'){var standardDefinitionUrl='https://img.youtube.com/vi/'+videoId+'/sddefault.jpg';var fallbackUrl='https://img.youtube.com/vi/'+videoId+'/hqdefault.jpg';var tempImage=new Image();tempImage.onload=function(){if(this.width===120&&this.height===90){setBgImage('url("'+fallbackUrl+'")')}else{setBgImage('url("'+standardDefinitionUrl+'")')}};tempImage.onerror=function(){setBgImage('url("'+fallbackUrl+'")')};tempImage.src=standardDefinitionUrl;return}
if(videoType==='vimeo'){setBgImage('url("https://vumbnail.com/'+videoId+'.jpg")');return}
if(videoType==='kinescope'){setBgImage('url("https://kinescope.io/'+videoId+'/poster/md.jpg")');return}
if(videoType==='boomstream'){setBgImage('url("https://play.boomstream.com/'+videoId+'/poster")');return}
if(videoType==='rutube'){setBgImage('url("https://rutube.ru/api/video/'+videoId+'/thumbnail/?redirect=1")');return}}
function t214__updateLazyLoad(recid){var scrollContainer=document.querySelector('#rec'+recid+' .t214__container_mobile-flex');var currentMode=document.querySelector('.t-records').getAttribute('data-tilda-mode');if(scrollContainer&&currentMode!=='edit'&&currentMode!=='preview'){scrollContainer.addEventListener('scroll',t_throttle(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
window.requestAnimationFrame=(function(){return(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60)})})();function t270_scroll(hash,offset){if(!hash)return;t270_checkLoad(hash,offset);var excludeHashes=['#!/tproduct/','#!/tab/','#opencart'];if(excludeHashes.includes(hash)){return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;t270_scrollToEl(hash,offset);if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_checkLoad(hash,offset){if(window.t270_loadChecked)return;var sliderWrappers=document.body.querySelectorAll('.t-slds__items-wrapper');if(!sliderWrappers.length)return;var lastWrapper=sliderWrappers[sliderWrappers.length-1];var sliderImgs=lastWrapper?lastWrapper.querySelectorAll('.t-slds__bgimg'):[];var lastImg=sliderImgs[sliderImgs.length-1];var imageUrl=lastImg?window.getComputedStyle(lastImg).backgroundImage:'';imageUrl=imageUrl.substring(5,imageUrl.length-2);var preloaderImg=document.createElement('img');preloaderImg.src=imageUrl?imageUrl:'';preloaderImg.addEventListener('load',function(){t270_scroll(hash,offset);window.t270_loadChecked=!0})}
function t270_scrollToEl(hash,offset){var SCROLL_DURATION_MS=500;var body=document.body;if(body.getAttribute('data-scroll'))return;var scrollTargetY=t270_getTarget(hash,offset);if(isNaN(scrollTargetY))return;var canSmoothScroll=window.CSS&&window.CSS.supports('scroll-behavior','smooth')&&'scrollBehavior' in document.documentElement.style;var userAgent=navigator.userAgent.toLowerCase();var isAndroid=userAgent.indexOf('android')!==-1;if(window.isMobile&&!isAndroid&&canSmoothScroll){body.setAttribute('data-scroll','true');window.scrollTo({left:0,top:scrollTargetY,behavior:'smooth',});setTimeout(function(){body.removeAttribute('data-scroll')},SCROLL_DURATION_MS)}else{t270_smoothScrollTo(scrollTargetY,SCROLL_DURATION_MS)}}
function t270_smoothScrollTo(targetY,duration=500){var body=document.body;var startY=window.scrollY||window.pageYOffset;var deltaY=targetY-startY;var startTime=performance.now();function easeInOutQuad(t){return Math.pow(t,2)}
function scroll(){var currentTime=performance.now();var elapsedTime=Math.min((currentTime-startTime)/duration,1);var ease=easeInOutQuad(elapsedTime);window.scrollTo(0,startY+deltaY*ease);if(elapsedTime<1){requestAnimationFrame(scroll)}else{body.removeAttribute('data-scroll');body.removeAttribute('data-scrollable');window.scrollTo(0,targetY)}}
body.setAttribute('data-scroll','true');body.setAttribute('data-scrollable','true');requestAnimationFrame(scroll)}
function t270_getTarget(hash,offset){var target;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"], div[id="'+hash.substr(1)+'"]');if(!target)return}
target=parseInt(target.getBoundingClientRect().top+window.pageYOffset-offset,10);target=Math.max(target,0);return target}