// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback values — the publishable key is safe to expose (RLS protects the data).
// These let the static build work on GitHub Pages even without env secrets.
const FALLBACK_URL = 'https://cadespdflpfmxzvvmxjl.supabase.co';
const FALLBACK_KEY = 'sb_publishable_3-6m8jutWH8QhS7MPgK4Bw_fu0qW1Vk';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});